baseURL = "https://mamadoulamineba.netlify.com/"
languageCode = "en-us"
title = "Mamadou Lamine Ba's Blog"
theme = 'erblog'
PygmentsCodeFences = true
PygmentsStyle = "emacs"
disqusShortname = "disqus_dwAWdkYCYm"
googleAnalytics = "UA-154944934-1"

[params]
    author = "Mamadou Lamine Ba"
    bio = """
    <p> I'm a senior software engineer interested in many different fields in computer science including Web Development, Databases, Integration, Microservices and much more.
     I like to learn new technologies and share knowledge with others.
    </p>
    """
    description = "I'm a senior software engineer interested in many different fields in computer science including Web Development, Databases, Integration, Microservices and much more. I like to learn new technologies and share knowledge with others."
    copyright = "Copyright &copy;2019. all rights reserved."
    ogimage = "https://mamadoulamineba.netlify.com/self/img/avater.jpg"
    favicon = "self/img/avater.jpg"


[[menu.main]]
    url = "/about/"
    name = "About Me"
    weight = 7


[taxonomies]
tag = "tags"
series = "series"
